# -*- coding: utf-8 -*-
"""PCOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zv6GacVoUIxHblxF3AkbgEo8IW3wCkEu
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
import seaborn as sns

dt = pd.read_csv('PCOS_Data.csv')
X = dt.iloc[:, 3:].values
y = dt.iloc[:, 2].values
dt.head()

"""# New Section

# New Section
"""

dt.isnull().sum()

dt.info()

sns.pairplot(dt.iloc[:, 1:5])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

print(X_train)

print(y_train)

print(X_test)

print(y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print(X_train)

print(X_test)

from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

pickle.dump(classifier, open('model.pkl','wb'))
model = pickle.load(open('model.pkl','rb'))

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))